version: '2'

services:
  mongodtldb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod

  invoiceservices.dtlmanager:
    image: invoiceservices.dtlmanager
    build:
      context: ./InvoiceServices.DTLManager
      dockerfile: Dockerfile
    depends_on: 
        - mongodtldb
    links:
        - mongodtldb
  